#!/bin/bash

# Run this script to combine the front end and back end into a deployable unit.

if [ -d regulately-front-end ] && [ -d regulately-back-end ]; then
    true
else
    echo 'Please run from a location where regulately-front-end and regulately-back-end are both subdirectories of the current directory.'
    exit 1
fi

if [ -e regulately ]; then
    echo -n 'Okay to delete existing "regulately" directory? '
    read answer
    if [ "$answer" = y ]; then
        rm -rf regulately
    else
        exit 1
    fi
fi

root=$(pwd)
out=$(pwd)/regulately

echo
echo 'Building the front end.'
cd "$root"
cd regulately-front-end
rm client/dist/bundle*
npm run dist

echo
echo 'Building the back end.'
mkdir "$out"
cd "$root"
cd regulately-back-end
cp -pr *.html "$out"
cp -pr *.py "$out"
cp -pr Procfile "$out"
cp -pr lib "$out"
cp -pr serve "$out"
cp -pr static "$out"
cd "$root"
cd regulately-front-end
cp client/dist/bundle*.js "$out"/static/bundle.js

echo
echo 'Done!  To run: regulately/serve'
