#!/bin/bash -e

# Run this script to combine the front end and back end into a deployable unit.

if [ -d regulately-front-end ] && [ -d regulately-back-end ]; then
    true
else
    echo 'Please run from a location where regulately-front-end and regulately-back-end are both subdirectories of the current directory.'
    exit 1
fi

if [ -e regulately ]; then
    echo -n 'Okay to delete existing "regulately" directory? '
    read answer
    if [ "$answer" = y ]; then
        rm -rf regulately
    else
        exit 1
    fi
fi

root=$(pwd)
out=$(pwd)/regulately

echo
echo 'Building the front end.'
cd "$root"
cd regulately-front-end
if [ -e client/dist/bundle*.js ]; then
    echo -n 'Okay to delete existing bundle.js? '
    read answer
    if [ "$answer" = y ]; then
        rm -f client/dist/bundle*
        npm run dist
    else
        echo 'Reusing existing bundle.js.'
    fi
fi

echo
echo 'Building the back end.'
mkdir "$out"
cd "$root"
cd regulately-back-end
cp -pr *.html "$out"
cp -pr *.py "$out"
cp -pr *.txt "$out"
cp -pr Procfile "$out"
cp -pr lib "$out"
cp -pr serve "$out"
cp -pr static "$out"
cd "$root"
cd regulately-front-end
cp client/dist/bundle*.js "$out"/static/bundle.js

echo
echo 'Making an archive.'
cd "$root"
name=regulately-$(date -u +'%Y-%m-%d-%H-%M-%S').zip
zip -r "$name" regulately

echo
echo 'Uploading to server.'
scp "$name" regulately@23.99.1.48:

echo
echo 'Restarting server.'
ssh regulately@23.99.1.48 bash -c 'sudo systemctl stop regulately; rm -rf regulately; unzip "'$name'"; sudo systemctl restart regulately'

echo
echo 'Done!'
