#!/usr/bin/env python

# Starts the Flask application server.

from app import app
import os

host = os.environ.get('REGULATELY_HOST', 'localhost')
port = int(os.environ.get('REGULATELY_PORT', '5000'))
app.run(host=host, port=port, debug=True)
